In [1]:
import numpy as np

In [2]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.ndim

2

In [5]:
arr.shape

(3, 3)

In [6]:
arr.size

9

In [7]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='float')

In [8]:
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [13]:
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
f=np.arange(0,30,5)
print("\nAsequential array with step of 5\n",f)
g=np.linspace(0,5,10)
print("\nAn array with 10 division ib range 0 to 5",g)


Asequential array with step of 5
 [ 0  5 10 15 20 25]

An array with 10 division ib range 0 to 5 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [23]:
arr1= np.array([[1,2,3],[4,5,6]])
print(arr1.flatten())

[1 2 3 4 5 6]


In [30]:
arr=np.array([[1,2,3,4],[4,3,2,1],[5,6,7,8],[9,8,7,6]])
print(arr)
print("\n",arr[1:,:2])
print("\n",arr[1:,::2])

[[1 2 3 4]
 [4 3 2 1]
 [5 6 7 8]
 [9 8 7 6]]

 [[4 3]
 [5 6]
 [9 8]]

 [[4 2]
 [5 7]
 [9 7]]


In [34]:
arr=np.array([2,3,4,5,6])
print("Addition by 1 is:",arr+1)
print("Subtraction by 1 is:",arr-1)
print("Multiplication so each element is:",arr*2)
print("squaring of each element is:",arr**2)
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("transpose is:",a.T)

Addition by 1 is: [3 4 5 6 7]
Subtraction by 1 is: [1 2 3 4 5]
Multiplication so each element is: [ 4  6  8 10 12]
squaring of each element is: [ 4  9 16 25 36]
transpose is: [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [47]:
arr= np.array([[1,2,3,4],[45,23,5,78],[98,78,55,21],[4,3,8,9]])
print(arr)
print("\n",arr.max())
print("\n",arr.max(axis=1))
print("\n",arr.max(axis=0))
print("\nSum is:",arr.sum())

[[ 1  2  3  4]
 [45 23  5 78]
 [98 78 55 21]
 [ 4  3  8  9]]

 98

 [ 4 78 98  9]

 [98 78 55 78]

Sum is: 437


In [49]:
a=np.array([[1,2],[4,5]])
b=np.array([[1,1],[1,1]])
print("Elementwise multplication\n",a*b)
print("Matrix Multiplication\n",a.dot(b))
            

Elementwise multplication
 [[1 2]
 [4 5]]
Matrix Multiplication
 [[3 3]
 [9 9]]


In [52]:
a=np.array([[1,2,3],[8,6,2],[3,1,5]])
print("sorted array\n",np.sort(a, axis=None))

sorted array
 [1 1 2 2 3 3 5 6 8]


In [62]:
a=np.array([[1,2],
          [3,4]])
b=np.array([[1,1],
            [1,1]])
print("vertical stacking\n",np.vstack((a,b)))     
print("Horizontal stacking\n",np.hstack((a,b)))
c=[5,6]
print("Coloumn Stacking\n",np.column_stack((a,c)))
print("concatenate\n",np.concatenate((a,b)))

vertical stacking
 [[1 2]
 [3 4]
 [1 1]
 [1 1]]
Horizontal stacking
 [[1 2 1 1]
 [3 4 1 1]]
Coloumn Stacking
 [[1 2 5]
 [3 4 6]]
concatenate
 [[1 2]
 [3 4]
 [1 1]
 [1 1]]


In [63]:
a=np.array([[1,2,3,4,5,6],
            [9,8,7,6,5,4]])
print("Horizontal split is:\n",np.hsplit(a,2))
print("Vertical split is:\n",np.vsplit(a,2))
print("Array splitis:\n",np.array_split(a,2))

Horizontal split is:
 [array([[1, 2, 3],
       [9, 8, 7]]), array([[4, 5, 6],
       [6, 5, 4]])]
Vertical split is:
 [array([[1, 2, 3, 4, 5, 6]]), array([[9, 8, 7, 6, 5, 4]])]
Array splitis:
 [array([[1, 2, 3, 4, 5, 6]]), array([[9, 8, 7, 6, 5, 4]])]
