# NUMPY ASSIGNMENT

In [5]:
import numpy as np

In [4]:
print(np.__version__)

1.19.0


In [10]:
a=np.zeros(10)
print(a)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
a=np.array([[2,4,5,7],[4,9,7,1]])
print("Size of array is: ",a.size)

Size of array is:  8


In [14]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [15]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [17]:
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [18]:
a=np.arange(15,22)
print(a[::-1])

[21 20 19 18 17 16 15]


In [19]:
s=np.arange(9)
x=s.reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
arr=np.nonzero([1,2,0,0,4,0])
print(arr)


(array([0, 1, 4], dtype=int32),)


In [28]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
a=np.random.uniform((3,3,3)
print(a)

[1.78780425 1.6113783  2.15098611]


In [35]:
a=np.random.random(100)
zmin,zmax=a.min(),a.max()
print(zmin,zmax)

0.0051294838616011695 0.9976774452058846


In [36]:
Z = np.random.random(30)
m = Z.mean()
print (m)

0.5024754610641208


In [42]:
z=np.ones((5,5))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [43]:
z=np.zeros((5,5))
z[1:-1,1:-1]=np.random.random()
print(z)

[[0.         0.         0.         0.         0.        ]
 [0.         0.62887183 0.62887183 0.62887183 0.        ]
 [0.         0.62887183 0.62887183 0.62887183 0.        ]
 [0.         0.62887183 0.62887183 0.62887183 0.        ]
 [0.         0.         0.         0.         0.        ]]


In [44]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [47]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [50]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [51]:
print (np.unravel_index(100, (6,7,8)))



(1, 5, 4)
